
export const CONSTANT = {
    ADD_CARD: "ADD_CARD",
    ADD_LIST: "ADD_LIST",
    REMOVE_CARD: "REMOVE_CARD",
    UPDATE_CARD: "UPDATE_CARD",
    DRAG_CARD: "DRAG_CARD",
    FETCH_TODOS_BEGIN: 'FETCH_TODOS_BEGIN',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
}